name: TekCeptional Solutions Beta 1
favicon: null
layout_spectrum: 0.9190629578661174
typography_spectrum: 0.63166
title: TekCeptional Solutions Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#217dc1'
    - '#d419d4'
    - '#a5a5a5'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
